using System;
using System.Collections.Generic;
using System.Text;

namespace CUDAnshita.API {
	public enum CUaddress_mode {
		CU_TR_ADDRESS_MODE_WRAP = 0,
		CU_TR_ADDRESS_MODE_CLAMP = 1,
		CU_TR_ADDRESS_MODE_MIRROR = 2,
		CU_TR_ADDRESS_MODE_BORDER = 3
	}

	public enum CUarray_cubemap_face {
		CU_CUBEMAP_FACE_POSITIVE_X = 0x00,
		CU_CUBEMAP_FACE_NEGATIVE_X = 0x01,
		CU_CUBEMAP_FACE_POSITIVE_Y = 0x02,
		CU_CUBEMAP_FACE_NEGATIVE_Y = 0x03,
		CU_CUBEMAP_FACE_POSITIVE_Z = 0x04,
		CU_CUBEMAP_FACE_NEGATIVE_Z = 0x05
	}

	public enum CUarray_format {
		CU_AD_FORMAT_UNSIGNED_INT8 = 0x01,
		CU_AD_FORMAT_UNSIGNED_INT16 = 0x02,
		CU_AD_FORMAT_UNSIGNED_INT32 = 0x03,
		CU_AD_FORMAT_SIGNED_INT8 = 0x08,
		CU_AD_FORMAT_SIGNED_INT16 = 0x09,
		CU_AD_FORMAT_SIGNED_INT32 = 0x0a,
		CU_AD_FORMAT_HALF = 0x10,
		CU_AD_FORMAT_FLOAT = 0x20
	}

	public enum CUcomputemode {
		CU_COMPUTEMODE_DEFAULT = 0,
		CU_COMPUTEMODE_EXCLUSIVE = 1,
		CU_COMPUTEMODE_PROHIBITED = 2,
		CU_COMPUTEMODE_EXCLUSIVE_PROCESS = 3
	}

	public enum CUctx_flags {
		CU_CTX_SCHED_AUTO = 0x00,
		CU_CTX_SCHED_SPIN = 0x01,
		CU_CTX_SCHED_YIELD = 0x02,
		CU_CTX_SCHED_BLOCKING_SYNC = 0x04,
		CU_CTX_BLOCKING_SYNC = 0x04,
		CU_CTX_SCHED_MASK = 0x07,
		CU_CTX_MAP_HOST = 0x08,
		CU_CTX_LMEM_RESIZE_TO_MAX = 0x10,
		CU_CTX_FLAGS_MASK = 0x1f
	}

	public enum CUjit_option {
		CU_JIT_MAX_REGISTERS = 0,
		CU_JIT_THREADS_PER_BLOCK,
		CU_JIT_WALL_TIME,
		CU_JIT_INFO_LOG_BUFFER,
		CU_JIT_INFO_LOG_BUFFER_SIZE_BYTES,
		CU_JIT_ERROR_LOG_BUFFER,
		CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES,
		CU_JIT_OPTIMIZATION_LEVEL,
		CU_JIT_TARGET_FROM_CUCONTEXT,
		CU_JIT_TARGET,
		CU_JIT_FALLBACK_STRATEGY,
		CU_JIT_GENERATE_DEBUG_INFO,
		CU_JIT_LOG_VERBOSE,
		CU_JIT_GENERATE_LINE_INFO,
		CU_JIT_CACHE_MODE,

		CU_JIT_NUM_OPTIONS
	}
}
